---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-karpenter
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: karpenter
                addonChartReleaseName: karpenter
                addonChartRepositoryNamespace: karpenter
                addonChartVersion: 1.1.2
                # using oci repostory already configure in argocd
                # argocd repo add public.ecr.aws --type helm --name aws-public-ecr --enable-oci
                addonChartRepository: public.ecr.aws
              selector:
                matchExpressions:
                  - key: enable_karpenter
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 1.1.2
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 1.1.2
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChartRepositoryNamespace}}/{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChartReleaseName}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}config/aws/{{values.addonChart}}/{{values.addonChart}}/values.yaml
              - $values/{{metadata.annotations.addons_repo_basepath}}config/aws/{{values.addonChart}}/{{metadata.labels.environment}}.yaml
            values: |
              nodeSelector: 
                {{.metadata.annotations.base_nodepool_labels}}
              settings:
                clusterName: {{metadata.annotations.aws_cluster_name}}
                interruptionQueue: {{metadata.annotations.karpenter_sqs_queue_name}}
              serviceAccount:
                name: {{metadata.annotations.karpenter_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.karpenter_iam_role_arn}}
      destination:
        namespace: '{{metadata.annotations.karpenter_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
