apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon-dependent-resources
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters: {}
  template:
    metadata:
      name: addon-dependent-resources
      finalizers:
        # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
        # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.workload_repo_url}}'
        path: '{{metadata.annotations.workload_repo_basepath}}{{metadata.annotations.workload_repo_path}}'
        targetRevision: '{{metadata.annotations.workload_repo_revision}}'
        helm:
          values: |
            karpenter:
              settings: 
                clusterName: {{metadata.annotations.aws_cluster_name}}
                eks_image:
                  x86_64: {{metadata.annotations.eks_image_x86_64}}
                  arm64: {{metadata.annotations.eks_image_arm64}}
      destination:
        name: '{{name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          backoff:
            duration: 1m
          limit: 60
